### ISSUE TITLE
[BALANCE] Prison time

### ISSUE THREAD

**Issue by troopakoopa** [iNCEPTION-RP/Feedback#22]
**What is the issue involving?**

The issue is with Prison time the amount of time served an nothing to do when you get to Prison. There us no interacting with anyone or anything while in Prison.

**In your opinion what is the way to fix this?**

I think time should be shorten by half till the server is in full bloom an there is a DOC in place, 

**Additional information**

**Comment by MintPoloo** [comment]
Highly disagree, we should be training newer cadets and learning the laws and times ready for when fully populated, it's all about risk at the end of the day if your willing to do them riskier activities which then lead to long jail time then that is down to the individual...

**Comment by troopakoopa** [comment]
I would totally agree with you if there were things in place to have RP in the Prison but with nothing in place i feel we are taking someone out of RP for over 2 hours max, removing a number count from a server that is trying to establish a community base. 

Do they have options of playing another toon absolutely. but most new players that might be running with other new players they fly in with would prob just log out as well. I say this on past experiences were i was told by people that they are logging because they can do things with there friends that are going to be in jail for over 45 minutes or longer an they just leave city, an go do something else an bring down city population.

**Comment by MintPoloo** [comment]
I think the fact that the amount of criminals which have been up to the jail so far and no one has complained may mean all understand the consequences and there is a max jail time on there, again it comes down to if people are willing to do the more advance criminal activities or kill people for instance they are going to do the time , as for activities in jail, there is always the option to go to jail as a group or attempt to go to the jail if your buddy is there, there is always ways to create RP people just need to use their minds a little more rather than just expect it all on a plate.

Another thing to add is that the police don't always "win" same with crims both sides get frustrating situations so sometimes we may spend the a hour chasing a dealing with crims and end up dying and lose all that time also. All narrows down to you win some and you lose some....

**Comment by troopakoopa** [comment]
Just because you don't hear them complaining doesn't mean that aren't complaining,  Look at fines, they were all cut on a ton of charges because of complaints but there is no feedback on it. 

I am just opening talking about this like it should be. Love the feed back to see others points of view. Why we have these forms.

**Comment by TheAlphaStrain** [comment]
In response to "as for activities in jail, there is always the option to go to jail as a group or attempt to go to the jail if your buddy is there, there is always ways to create RP people just need to use their minds a little more rather than just expect it all on a plate."

Let's play that out. Say 2, 3 or 4-5 of you decide we want to go to jail together. From past experience myself, I've known this to happen as a send off to people flying out. In another city where max time was 45 minutes (aka 45 months), people would go to jail together just for a little bit of fun then logout because they gotta wait 45 minutes and, like Troopa said, go do something else. Thus, now we've effectively lost that amount of population. 

Now, that being said, if me and say two other people or however many and you guys wanna slap us with however many stackable charges or however the case may be and we ALL get 120 minutes. What, pray tell, are we going to do for 2 whole hours? I can think of a few ideas. But I would honestly love to see a group of people entertain themselves for 2 hours singing kumbaya. 

That being said... even if there were things to do, I honestly think it's still too long. I think having lower prison time will create more RP. Especially with repeat offenders. They're in, they do whatever RP while in the clink, they get out, they're likely going to do it again. I've known people to go right back in after getting out. That's the character they chose to play. 

I feel like you're taking it too literal. There is a way of them getting the max for what they did. Just because you lower the jailtime does not mean you can't keep stacking the charges on them with other stuff, killing their bank account. It's not hard to rack up that time.

If I shoot a cop with a Desert Eagle, there's an automatic 32 minutes right there. I then proceed to steal a local vehicle and speed away. There's 52 minutes. Then you start chasing me, there's 57 minutes. Say it all started at a store robbery police witnessed. There's 70 minutes. Perhaps I forgot I had some drugs in my pockets. Now we're up to 88 minutes. All this can be achieved within 5-10 minutes. 

So now that 5-10 minutes of, could be, fun RP on both sides turns into 88 minutes of dull nothingness in prison. Just saying.

**Comment by AthanAlonzo** [comment]
From my side I agree and disagree, yes the max jail time is boring but, there is a reason why there is a max, if it is unlimited it will be even worse.

Stating that, there will be a reason for individuals that got the max jail time, what actions have you done? what is the reason behind it why said individual got the max jail time? maybe it is a perfect time for said individual to reflect on his actions for that amount of time as well, and better or do less next time?

Shortly stated, Don't want to do the time? don't do the crime basically.

**Comment by ixhal** [comment]
We have spoken about this many times as a staff team and currently on the bucket list is to add a job to prison, This job wont remove time but will gain you cash and give you something to do, I don't think we have ever had anyone jailed for the maximum time limit we set yet so I don't think changing the cap on it is necessary, Also you can fly out of that character and go back in on another and the time will continue to go down, Don't know if many people know that but that is how we wanted it from the beginning. Will be closing this for now, If any more issues arise feel free to open up a new thread.
