### ISSUE TITLE
[BALANCE] Using Only What The City Offers

### ISSUE THREAD

**Issue by TheAlphaStrain** [iNCEPTION-RP/Feedback#30]
**What is the issue involving?**
Let me start by saying that I understand the purpose is to create an RP experience. But, I feel like if it's not in the city, if you can't get it in the city by legit means, ie. an Attack Chopper, then I feel like it shouldn't be used. There's been quite a few instances of this recently as well. For example, turning people into animals. Now, this is not me being mad or disgruntled about asking personally if I can make one of my characters into a career criminal called Alvin Seville, voice and all and being told no. The ONLY reason I asked is BECAUSE I was seeing an increase of animal peds in the city. Then I get told "I would love to but we cant atm because if I do it for you then ill have to do it for everyone that asks.." yet it had been happening. (Haven't actually seen it much since I asked about it.)

Albeit I get that it's probably all staff, but it just prompts people to see it and want to do it but it's only staff. Another thing, going back to the attack chopper thing... no one, including PD can get one. But I remember a specific incident where we tried to create, what we thought, would be a hilarious, slow, "high speed" chase using bulldozers to create some RP. What did we get in return for that? The inability to get anymore bulldozers. Yeah we flipped two cars. But what's worse? Destroying multiple vehicles with an attack chopper or flipping 2 cars with a dozer?

On another note, I am being told about explosives being a thing. I know what I know, and I am severely questioning it. I get a call as a lawyer and I all of a sudden have to defend someone against bomb threats and explosion charges? How? 

**In your opinion what is the way to fix this?**
It's just my opinion to not use anything you can't otherwise obtain in the city. Not trying to stop RP rather promote legit RP through repetition with different scenarios. If there's only a couple individuals who can, it's not really affording everyone the opportunity to be creative with the same scenario.

**Additional information**
Think I said all I needed to.

**Comment by ixhal** [comment]
At the end of the day everyone that changes into a animal or spawns in a attack heli knows what they are doing and can be trusted, These things cant be give out to everyone and if you want people to stop trying to make peoples days better by being animal peds/spawning in a attack helicopter when police are out numbering criminals then that is fine and again its just ur opinion I see no one else has upvoted this or downvoted it or even replied so I will close the ticket and if it continues to be a issue feel free to come and open up another issue. These things was put in the game to make things better, The who C4 situation is something to get people used to the idea that they can and will more than likely be used in the future and we have to plan ahead.

Again I have not spawned anything in other than turning my self into some animals now and again to make peoples days better. It feels to me that you are upset because you cant do these things and that is a valid reason but you should also see the point of view from others, Its a fun experience to see a monkey running around with PD, Its fun to roleplay having a dog that actually listens to you.

Just to touch on the attack heli situation I am not a big fan of this happening too and it probably should not happen, The first time we did this was because crims took bulldozers to MRPD and was destroying cars with no roleplay, We as staff though it was wrong but did not want to punish the people involved so instead we gave them a friendly warning with a attack helicopter. 

So as I said ill close this issue as no else seems to want to speak up on the matter.
