### ISSUE TITLE
[BALANCE] Shift Time on the Elegy Retro Custom 

### ISSUE THREAD

**Issue by TheeSaberWolf** [iNCEPTION-RP/Feedback#34]
Im having trouble with the shift times between gears it would be a great car but it has like  1 - 1.5 sec shift time and it kills the acceleration of the vehicle would be way better if it shifted with the rest of the cars

**Comment by driftoooo** [comment]
Hi there TheeSaberWolf, 
 Your issue is definitely present! It almost feels as if you're triple-checking that you've not put it into 1st instead of 3rd 😂 
 
 I've significantly reduced the shift rate from 2 seconds to 0.65 seconds. 
 
 These changes **should hopefully** be available after the next restart.
 
 Thank you for submitting this vehicle-related bug report, I'll be closing it at this time! All feedback is greatly appreciated!

**Comment by TheeSaberWolf** [comment]
Hell yeah I’ve just been grinding it till I found it
