### ISSUE TITLE
[ENHANCEMENT]

### ISSUE THREAD

**Issue by TheAlphaStrain** [iNCEPTION-RP/Feedback#5]
**What feature you want to improve**
Crafting Table

**How could this feature be improved? Please describe your idea as much as possible**
I think it would be good if you could use the crafting table inside a storage space such as the trunk of your car or house storage. 

**Additional information**
Due to the fact that crafting 1x1 Emergency Stim packs are a pain if you're doing multiple since we seem to always be running out and you can only craft 1 at a time because you can only carry 1 at a time. Having to open and back out of all these menus even if you want to make just 10 is a tad much. Let alone 30+

**Comment by bloombydee** [comment]
This is already something we plan to do when we have furniture for houses, as well as more balancing for the power of the stimpack. Until that point, we'll have to leave it the way it is because we can't have ppl carrying multiple stims and your suggestion would require a major rewrite of the inventory, and we'd rather spend that time on new content. Thank you for the feedback though :)
