### ISSUE TITLE
[BALANCE] House Robberies 

### ISSUE THREAD

**Issue by troopakoopa** [iNCEPTION-RP/Feedback#6]
**What is the issue involving?**

House Robbery

**In your opinion what is the way to fix this?**

I Feel that house robberies are to easy an are being hit way to often using Normal Lock Picks. I Feel that the Advanced Lockpicks that Electronics class crafts should be used for house robberies not normal lock picks. 

**Additional information**

By doing this will bring more RP to the City because people will need to interact more with other one to figure out how to do house robberies an two will have to buy advance lockpicks off someone that has one or can make them.

**Comment by ixhal** [comment]
There is benefits to using a advanced lockpick that I cant disclose publicly, also the breaking in mini-game is easier with the advanced lockpick, The original idea was to do this but because its the only real content for criminals at this point we cant do that just yet but its possible in the future.
Thanks for the feedback!
